#!/bin/bash
#$ -l h_vmem=11G
#$ -pe smp 32
#$ -l gpu=4
#$ -l gpu_type=volta
#$ -l h_rt=240:0:0
#$ -cwd
#$ -j y
#$ -m beas
#$ -l h=sbg3

#echo $SGE_HGR_gpu

export CUDA_VISIBLE_DEVICES=${SGE_HGR_gpu// /,}
#echo $CUDA_VISIBLE_DEVICES
module load anaconda3/2020.02
module load cudnn/7.6-cuda-10.1
#nvidia-smi
conda activate asteroid

# Replace the following line with a program or command
bash run.sh

# Generated by Job Script Builder on 2020-09-20
# For assistance, please email its-research-support@qmul.ac.uk